//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated manually for Rider.
//     Changes to this file affect behavior and persist in user settings.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBridgeServer.Properties
{
    using System;
    using System.Configuration;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ManualSettingsBuilder", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Settings1 : ApplicationSettingsBase
    {
        private static readonly Settings1 defaultInstance = (Settings1)Synchronized(new Settings1());
        public static Settings1 Default => defaultInstance;

        [UserScopedSetting()]
        [DefaultSettingValue("5000")]
        internal int ServerPortSetting
        {
            get => (int)this["ServerPortSetting"];
            set => this["ServerPortSetting"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        internal bool IsServerRunning
        {
            get => (bool)this["IsServerRunning"];
            set => this["IsServerRunning"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        internal bool LeftStickInvertX
        {
            get => (bool)this["LeftStickInvertX"];
            set => this["LeftStickInvertX"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        internal bool LeftStickInvertY
        {
            get => (bool)this["LeftStickInvertY"];
            set => this["LeftStickInvertY"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        internal bool RightStickInvertX
        {
            get => (bool)this["RightStickInvertX"];
            set => this["RightStickInvertX"] = value;
        }

        [UserScopedSetting()]
        [DefaultSettingValue("false")]
        internal bool RightStickInvertY
        {
            get => (bool)this["RightStickInvertY"];
            set => this["RightStickInvertY"] = value;
        }

        // Save all changes
        internal void SaveSettings()
        {
            Save();
        }
    }
}
