//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBridgeServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings_Designer : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_Designer defaultInstance = ((Settings_Designer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_Designer())));
        
        public static Settings_Designer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int ServerPortSetting {
            get {
                return ((int)(this["ServerPortSetting"]));
            }
            set {
                this["ServerPortSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool IsServerRunning {
            get {
                return ((bool)(this["IsServerRunning"]));
            }
            set {
                this["IsServerRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool LeftStickInvertX {
            get {
                return ((bool)(this["LeftStickInvertX"]));
            }
            set {
                this["LeftStickInvertX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool LeftStickInvertY {
            get {
                return ((bool)(this["LeftStickInvertY"]));
            }
            set {
                this["LeftStickInvertY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool RightStickInvertX {
            get {
                return ((bool)(this["RightStickInvertX"]));
            }
            set {
                this["RightStickInvertX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool RightStickInvertY {
            get {
                return ((bool)(this["RightStickInvertY"]));
            }
            set {
                this["RightStickInvertY"] = value;
            }
        }
    }
}
